package com.izv.hibernate;
// Generated 30-ene-2015 22:46:08 by Hibernate Tools 4.3.1



/**
 * Fotos generated by hbm2java
 */
public class Fotos  implements java.io.Serializable {


     private Integer id;
     private Integer idinmueble;
     private String nombre;

    public Fotos() {
    }

    public Fotos(Integer idinmueble, String nombre) {
       this.idinmueble = idinmueble;
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdinmueble() {
        return this.idinmueble;
    }
    
    public void setIdinmueble(Integer idinmueble) {
        this.idinmueble = idinmueble;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


