package com.izv.hibernate;
// Generated 27-ene-2015 22:43:47 by Hibernate Tools 4.3.1



/**
 * FotosId generated by hbm2java
 */
public class FotosId  implements java.io.Serializable {


     private int idfoto;
     private String nombre;

    public FotosId() {
    }

    public FotosId(int idfoto, String nombre) {
       this.idfoto = idfoto;
       this.nombre = nombre;
    }
   
    public int getIdfoto() {
        return this.idfoto;
    }
    
    public void setIdfoto(int idfoto) {
        this.idfoto = idfoto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FotosId) ) return false;
		 FotosId castOther = ( FotosId ) other; 
         
		 return (this.getIdfoto()==castOther.getIdfoto())
 && ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdfoto();
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         return result;
   }   


}


